GET http://localhost:3000/api

### Insert an allergen groups
POST http://localhost:3000/api/users/login
content-type: application/json

{
    "email" : "sami@sszzz.com",
    "password" : "1235"
}

### Register a new user
POST http://localhost:3000/api/users/register
content-type: application/json

{
    "email" : "sami@sszzz.com",
    "password" : "1235",
    "name" : "Sami"

}